---
# defaults file for roles/win_ad_install
ad_domain_name: ad1.6bd1.example.opentlc.com
ad_safe_mode_password: "{{ansible_password}}"
ad_admin_user: "admin@{{ ad_domain_name}}"
ad_admin_password: "{{ansible_password}}"